configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/MiloGithub%2Fmilosthirdproject-3ec900e35618148ec956a52250dc88265c33d5b5650e339638c48fc9e9a5f4ee.yml
